# Generated by Django 5.2.8 on 2025-12-01 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Код подтверждения",
            ),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="expiration",
            field=models.DateTimeField(verbose_name="Срок действия"),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["expiration"], name="users_email_expirat_da9fe2_idx"
            ),
        ),
    ]
