# Generated by Django 5.2.7 on 2025-11-12 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_emailverification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
