# Generated by Django 5.2.8 on 2025-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_emailverification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="code",
            field=models.UUIDField(unique=True),
        ),
    ]
